channels:
  - conda-forge
dependencies:
  - fastapi
  - bokeh
  - bokeh-fastapi
  - panel
  - param
  - geopandas
  - holoviews
  - numpy
  - matplotlib
  - pytest
  - pip
  - pip:
    - git+https://github.com/DTC-Glaciers/dtcg@v0.3.0
    - git+https://github.com/gampnico/oggm@feat-dtcg
    - -e .
